### ISSUE TITLE
Error /data on update from Magisk

### ISSUE THREAD

**Issue by Bruno-FGM** [nift4/microg_installer_revived#166]
I have the following error when updating to version 4.1.0-0

```
Checking if file path of com.android.vending is on /data
- ERROR: expected microG Companion / Play Store install path to be on /data, but it's /system/priv-app/Phonesky/Phonesky.apk
! Installation failed
```

**Comment by Bruno-FGM** [comment]
I tried installing companion from F-droid and got an error about not being the same signature that the one installed.
I remember sometime ago that I had to install as normal apk but could not find the apk... 
Could you tell me how to do it?

**Comment by nift4** [comment]
https://github.com/microg/GmsCore/releases/tag/v0.3.2.240913 try com.android.vending-84022604.apk

**Comment by kibirisu** [comment]
For me, it fixes the issue

**Comment by Bruno-FGM** [comment]
If fixes the  issue for me too... but I have no idea why :)
Will I need to do the same thing for any new update or was it only a one shot? Do not believe that I had to  do  anything in previous update. 
Anyway  thx for the quick and efficient answer!

**Comment by hieu-van** [comment]
> Have you followed the install instructions, https://github.com/nift4/microg_installer_revived?tab=readme-ov-file#installation
> 
> Especially the "Install microG 0.3.2 and Companion (or real Play Store) as normal user app" ?

Damn I missed that.

**Comment by nift4** [comment]
> Will I need to do the same thing for any new update or was it only a one shot?

I recommend just setting up F-Droid with the microG repository and download updates from there. In theory you won't even have to update this module anymore after that, but you optionally can (after updating the microG APK).

> Do not believe that I had to do anything in previous update.

This mechanism is new in 4.x, I added it because it fixes a lot of the long-standing bugs of this installer. It was supposed to be automated, but as visible by your cases, that automation was not reliable, and that caused issues.

**Comment by Bruno-FGM** [comment]
Thx a lot for the great support and explanation
