### ISSUE TITLE
v4 - what's the point?

### ISSUE THREAD

**Issue by Uj947nXmRqV2nRaWshKtHzTvckUUpD** [nift4/microg_installer_revived#183]
what's the point of having to install microg manually before this module, if the whole purpose of this module was to assist microg installation in the first place?

why would this module be needed anymore?

**Comment by nift4** [comment]
- microGOverlay for making network location actually work on AOSP-ish ROMs
- workarounds for some stock ROMs
- microG's MapsV1 API for antiquated apps
- GsfProxy included
- systemful install
- correctness checks & documentation (it's easy to do things wrong after improperly debloating google play services because uninstalled doesn't mean uninstalled in Android - it's the top 1 root cause for issues reported here)

**Comment by nift4** [comment]
> why do i have to install microg before now? 

A lot of people shot themselves in the foot by using Play Integrity Fix, Universal SafetyNet Fix, Shamiko, Magisk Hide, Magisk DenyList or KernelSU unmount modules applied to microG, which will cause Magisk to undo all modifications from microG's point of view. Which means, microG won't be able to see it's own APK and will crash because it can't load it's own data. A workaround for this is to also have it installed as user app (which means it'll be an updated system app) because the APK on /data will remain visible, and hence it will find it's data and not crash.

However, I can't automate that because when updating microG, Magisk Manager will be force stopped because it declares a dependency on GMS SSL modules and Android system will restart all dependant apps of an updating app. This means during module installation, Magisk Manager will appear to be crashing, which has confused a lot of people.

The only viable solution is to install the microG APK either before or after the module install. I used to go with latter solution telling people to install the same APK again manually to fix the crashes, but I got very very large amounts of emails and issues due to people not reading the instructions carefully.

Hence, I went with the last route, having people install the APK before installing the module.

Another advantage of this is that incomplete/impromper debloats will stop with APK installation failure instead of random microG crashes, which is a lot better user experience (who likes unexplainable crashes because they used a debloater which doesn't debloat in a sufficient way? It's not intuitive, and again, has caused lots of people to contact me and ask for help).

The error message you posted: "redeclare permission com.google.android.googleapps.permission.GOOGLE_AUTH.writely com.google.android.gsf"
also means you failed to uninstall it properly. You need to delete the APK files of GmsCore, GoogleServicesFramework and Play Store from the file system and make sure to install the app in all of Android's user (multi-user, parallel space and work) profiles, then that should go away.

**Comment by nift4** [comment]
This is the job of gms_delete.zip, I adapted it for your OnePlus system, please let me know if it works: 
[gms_delete.zip](https://github.com/user-attachments/files/17334031/gms_delete.zip)

**Comment by nift4** [comment]
So something like this doesn't work either? 
[gms_delete.zip](https://github.com/user-attachments/files/17339426/gms_delete.zip)

**Comment by Iey4iej3** [comment]
> The only viable solution is to install the microG APK either before or after the module install. I used to go with latter solution telling people to install the same APK again manually to fix the crashes, but I got very very large amounts of emails and issues due to people not reading the instructions carefully.
> 
> Hence, I went with the last route, having people install the APK before installing the module.

It seems that there are still issues: if the user *upgrades* MicroG to an unsupported version, then MicroG might stop working tacitly, without any warning.

**Comment by nift4** [comment]
> It seems that there are still issues: if the user upgrades MicroG to an unsupported version, then MicroG might stop working tacitly, without any warning.

I am not aware of any such issue. The supported version check is for the sake of avoiding privilegied permission consistency check failures causing a bootloop. Upgrading microG by just installing the new APK does not trigger these checks.

You may have been hitting issues due to an outdated security spoofing patch in your ROM. Refer to microG self-check and 0.3.6 changelog for more information.

**Comment by Iey4iej3** [comment]
> > It seems that there are still issues: if the user upgrades MicroG to an unsupported version, then MicroG might stop working tacitly, without any warning.
> 
> I am not aware of any such issue. The supported version check is for the sake of avoiding privilegied permission consistency check failures causing a bootloop. Upgrading microG by just installing the new APK does not trigger these checks.
> 
> You may have been hitting issues due to an outdated security spoofing patch in your ROM. Refer to microG self-check and 0.3.6 changelog for more information.

Thanks. Right now, there is no real issue, but a technical issue: if you update the microG APK, and then you are no longer capable to update the module due to version checking.

**Comment by nift4** [comment]
> Right now, there is no real issue, but a technical issue: if you update the microG APK, and then you are no longer capable to update the module due to version checking.

This is alleviated by me supporting the newest microG version there is at the point of releasing an update. Only if someone delays updating the module until a new microG release is out, I must release a new version for that person to update. But in the grand scheme of things, minor module updates of this module usually provide no advantage at all for users with a working setup, so it does not matter.
