### ISSUE TITLE
Directly use MicroG apk from microg homepage

### ISSUE THREAD

**Issue by ioctl-user** [nift4/microg_installer_revived#21]
Is it possible to download MicroG apps directly from official microg site while building repository or while installing Magisk module instead of using apps stored in this repository?

This should improve clearness of the module.

**Comment by nift4** [comment]
> Is it possible to download MicroG apps directly from official microg site while building repository
Nope because there is no actual build process, that what is in the README is what the magisk repo is doing automatically. That can't be configured.

> or while installing Magisk module
That way would need internet at install time, some users download the zip and don't always have internet.

> This should improve clearness of the module.
You can compare hashes - it's the same apk. Though I understand your concern, I think that is the best way.

**Comment by ioctl-user** [comment]
Ok.
