### ISSUE TITLE
system soft restarting upon update

### ISSUE THREAD

**Issue by fusionneur** [nift4/microg_installer_revived#57]
updated from 2.6.3 to 3 and after reboot, the system gui keeps restarting. had to revert. any1 experiencing the same?

**Comment by nift4** [comment]
what do you mean by, system gui restarting? what rom are you on? stock?

**Comment by nift4** [comment]
does this work? https://temp.nift4.org/microG_Installer_Revived.zip

**Comment by nift4** [comment]
usb adb shell?

**Comment by nift4** [comment]
does the system boot without xprivacylua or xposed at all?

**Comment by nift4** [comment]
The root cause seems to be an XPrivacyLua crash, which causes the RecoveryParty app watchguard to kick in before the system has finished booting, which causes the system to crash due to an old Android bug... I really don't understand the correlation with my installer though, but this definitefly is not something I can fix, I'm sorry.

**Comment by nift4** [comment]
try to uninstall XPLua Pro app

**Comment by Joduai** [comment]
> any1 experiencing the same?

I experienced problems but of a different nature on my moto G8 with unofficial arrowos 13. 
Updating from 2.6.3 to 3.0 in magisk breaks during the installation. I suppose it might be caused by Phonesky.apk I had in /data/adb. I'm only guessing as no magisk installation log is available when the installation breaks.

After first reboot screen started flickering. I have this problem every time after a fresh magisk installation, but after reboot everything seems working fine. But not this time. After booting the touchscreen stopped responding. Two reboots later touchscreen kind of worked, but the nanolx playstore was gone.
Uninstalled v.3.0, rebooted and reverted back to 2.6.3. Everything works fine along with nanolx playstore.

I use bare magisk w/o any xposed/lsposed framework, with enabled systemless host and zygisk. Beside systemless hosts module I have only energized protection.
I don't know what additional info I can share, and how to grab it,  especially during installation.
Logcat is flooded without even launching magisk, so I barely check it out.

**Comment by nift4** [comment]
I didn't change anything related to Play Store install code at all, except one visual message.

I'm thinking these problems arise from the fact that the module contains an new overlay, which erases package caches when installed and causes them to regenerate in unfortunate ways. The root cause of the issues however is out of my control. I can only suggest you to try and flash my (official) 3.0 over your repackaged version, because nothing should change.
