### ISSUE TITLE
No GPS in Maps

### ISSUE THREAD

**Issue by bphd** [nift4/microg_installer_revived#68]
I haven't been able to gather many elements. I have that, but Idk in what it can help

```łog
MNLD    : mnld_gps_controller_mnl_nmea_timeout: GPS not in started done state, ignore timer for NMEA monitor!!!
SQLiteLog: (13) statement aborts at 7: [INSERT OR REPLACE  INTO stats(tenantid,statsvalue) VALUES (?,?)] database or disk is full
ServiceManager: Permission failure: android.permission.HIGH_SAMPLING_RATE_SENSORS from uid=pid=22548
View    : requestLayout() improperly called by com.google.android.libraries.geo.mapcore.internal.ui.CompassButtonView{1ac8904 I.E...... ......I. 600,124-696,220 #7f0b00f9 app:id/base_compass_button} during layout: running second layout pass
android.hardware.gnss@2.1-service-mediatek: update_gps_status:   status=1
android.hardware.gnss@2.1-service-mediatek: update_gps_status:   status=3
gps_controlller: linux_gps_init: Status (18) 
gps_controlller: mtk_gps_sys_gps_mnl_callback: MTK_GPS_MSG_FIX_READY,GET_RTC_FAIL
```

And I get App won't run without Google Play services, which are not supported by your device.

**Comment by nift4** [comment]
Try "GPS Test" app from F-droid.. If it shows nothing, it's unrelated to microG. microG only handles network location.

Are all self test boxes checked

**Comment by bphd** [comment]
I land on the "status" tab where I have a list of satellites

PhoneSky signature
Background location
SMS
Not checked

**Comment by nift4** [comment]
"PhoneSky signature" is your problem regarding "App won't run without Google Play services, which are not supported by your device", fix it

and please grant all permissions

**Comment by bphd** [comment]
How?

The remaining permissions don't permit to be toggled on, Idk why

**Comment by nift4** [comment]
Are you on the latest version of the module? did it show any errors while installing?

**Comment by bphd** [comment]
Yeah I think

**Comment by nift4** [comment]
...what's your module version?
did it show any errors while installing?

**Comment by bphd** [comment]
I installed the LSPosed module and now the PhoneSky is OK

But I still have no GPS

**Comment by nift4** [comment]
please start fresh. you serevely fucked up your installation - follow the guide exactly after going an factory reset, make signature spoofing work from the start and use 3.1.0-0 module

**Comment by bphd** [comment]
I don't want to lose all my data

The ROM was giving spoofing permission to revived, but revived did nothing with it

**Comment by nift4** [comment]
I don't think "You fucked up your installation" can be misunderstood. Use a backup app.

If your ROM already supports the signature spoofing permission, installing the LSPosed module breaks it.
The issue you described regarding permissions that cannot be enabled happens **only** if an user improperly removes (or not at all removes) Google applications in your ROM or the user is using an ancient version of the module.
If Google Maps can't get an GPS fix, it's totally unrelated to this module. Only network location would be related.
If SafetyNet returns null, internal microG state is broken (maybe due to installing over GApps).

I asked you concrete questions a few times, however you completely ignored them. You just did random things that made the issue even worse.
You neither mentioned your device name, Android version, ROM name, how you installed the module or anything else. You did not even think of the fact that self check issues are problems you need to solve.

What do you except of me to solve all these?? I'm not getting paid for this, I'm doing support out of good will and I don't have any desire to support people who can't accept the most minor of inconvenience and except me to fix all their issues magically while they are ignoring my advice.

**Comment by bphd** [comment]
Maybe the module is supposed to breaks the signature, but here it checks teh condition where the app hasn't been able to spoof the signature itself

MGIR is latest on my device, the ROM comes without any GApps, I've only installed another MicroG to try but it's inactivated

I tried to reply to what I can

Moon, A12, crDroid, I installed the module via MagiSK. I tried to solve the self check. I had the signature checked. I just couldn't find for SMS or background

You misunderstood me, I don't try to use your service. I just want this implementation to be more resilient, because it's the one who have exactly what I want. Sorry if you feel ignored

**Comment by nift4** [comment]
If you have no connection in microG apps, try enabling Network access in App-Info of all microG apps.
If you install the App "SatStat", you can diagnose location services as opposed to your GPS chip only. Does it show you "network location"?
Is the location permission granted now? If yes, is it possible to remove it? You don't need to actually disable it, but Android should complain if you try. If it does not, something regarding the NLP overlay is wrong, and we can diagnose further.
You said that when you reboot, GSF disappears. Is GSF or the app that needs it in Magisk DenyList?

**Comment by bphd** [comment]
Enabling network access? I don't see such permission

All MicroG apps? How can I identify them all for sure? I just know the Helper one

**Comment by nift4** [comment]
"Enabling network access? I don't see such permission" App-Info > Network and Internet > Allow network usage or similar

"All MicroG apps? How can I identify them all for sure? I just know the Helper one" They all have microG in the name ;)

"I get a fix in SatStat. Where is written "network location?". I granted the location temporarly to SatStat" See three dots > Legend on how to interpret the information

"As a location provider I can't remove the permission" Perfect, that's what it should do

"Everything is denied on the DenyList, except what needs root and what I can't deny" This is an sereve issue with your configuration, BECAUSE: If you put something on the DenyList, all magisk modules **including this one** will disappear from that app's POV. You should only check apps that require it.

"If I get out GSF and the concerned apps from the DenyList I can get a fix perfectly

When GSF got out of DenyList, it systemize itself automatically" Perfect.

**Comment by bphd** [comment]
It seems to work even if GSF is denied

**Comment by nift4** [comment]
"It should be soooooo good to add what parameter permit what function in the manual." Well, network access is granted by default on 99% of installs - in fact including you I had 2 complaints after I added automation to grant it.

DenyList is just not excepted to be checked for all apps, that's an magisk thing - it also breaks original Google Play Services in subtle ways.

Do you have location modules installed and configured? If yes, it should improve the reliability of network location.

**Comment by bphd** [comment]
Location modules?

**Comment by nift4** [comment]
If you open microG settings, there's an "Location modules" button. Did you install any?
If not, you can download "Mozilla", "Apple" and "Nomantim" from F-Droid and then enable them there

**Comment by bphd** [comment]
That's replacement of Google Location Services? If yes I'm wondering why custom ROM doesn't integrate those kind of thing per default, a little bit like FLOSSAPPS. At least in their non Google flavor

**Comment by nift4** [comment]
Yes it is, though microG is required for it to actually work. This is why I ship requires configuration in this module.

**Comment by bphd** [comment]
I downloaded and activated dozen of those, though I'm not sure what it will change in my situation considering that I already had fix in some situation

**Comment by bphd** [comment]
It's so tricky, now that I have installed some Google Account, CityMapper restart to hang at start, like it have a problem with the state of google services
